List lines = Arrays.asList(new String[]{"one", "two   three"})
Parser.parse(lines).grab("e")
Parser.parse(lines).grab("ee")
Parser.parse(lines).grab("e").wordcount()
Parser.parse(lines).grab("ee").wordcount()
Parser.parse(lines).grab("z")
Parser.parse(lines).grab("z").linecount()
Parser.parse(lines).grab("z").wordcount()
Parser.parse(lines).grab("z").linecount().grab("0").linecount()
Parser.parse(lines).echo()
Parser.parse(lines).echo().grab("e t")
Parser.parse(lines).echo().grab("et")
